version: '3.8'
services:
  #PHP Service
  app:
    image: hieubossgr/jenkins-docker-php:latest
    restart: unless-stopped
    volumes:
      - ./:/var/www/html

  #Nginx Service
  webserver:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - /home/web/nginx.conf:/etc/nginx/conf.d/default.conf
