version: '3.8'
services:
  #PHP Service
  app:
    image: hieubossgr/jenkins-docker-php:latest
    restart: unless-stopped
    volumes:
      - ./:/usr/share/nginx/html

  #Nginx Service
  webserver:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html
      - /home/vega/nginx.conf:/etc/nginx/conf.d/default.conf
